# Screen
WINDOW_WIDTH  = 800
WINDOW_HEIGHT = 600

DISPLAY_WIDTH  = WINDOW_WIDTH / 3
DISPLAY_HEIGHT = WINDOW_HEIGHT / 3

BG_COLOR = (36, 36, 36)

# Sprite
SPRITE_SHEET = "assets/sprites.png"
SPRITE_COLOR_KEY = (255, 0, 255)
SPRITE_SIZE = 16

# Entity
ENTITY_SIZE = 16
PLAYER_HEALTH = 100
ENEMY_HEALTH = 100

# Game
FPS = 60
DAMAGE_DISPLAY_TIME = 2
